/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Agenda extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 963529937;

	/**
	 * The singleton instance of <code>agenda</code>
	 */
	public static final Agenda AGENDA = new Agenda();

	/**
	 * No further instances allowed
	 */
	private Agenda() {
		super("agenda");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.untref.agendauniversitaria.tables.Alumnomateria.ALUMNOMATERIA,
			org.untref.agendauniversitaria.tables.Alumnos.ALUMNOS,
			org.untref.agendauniversitaria.tables.Cincomasdescargados.CINCOMASDESCARGADOS,
			org.untref.agendauniversitaria.tables.Documentos.DOCUMENTOS,
			org.untref.agendauniversitaria.tables.Eventos.EVENTOS,
			org.untref.agendauniversitaria.tables.Materias.MATERIAS);
	}
}
