/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CincomasdescargadosRecord extends org.jooq.impl.TableRecordImpl<org.untref.agendauniversitaria.model.tables.records.CincomasdescargadosRecord> implements org.jooq.Record5<java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Double> {

	private static final long serialVersionUID = 2100033131;

	/**
	 * Setter for <code>agenda.CincoMasDescargados.Documento</code>.
	 */
	public void setDocumento(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>agenda.CincoMasDescargados.Documento</code>.
	 */
	public java.lang.String getDocumento() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>agenda.CincoMasDescargados.Materia</code>.
	 */
	public void setMateria(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>agenda.CincoMasDescargados.Materia</code>.
	 */
	public java.lang.String getMateria() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>agenda.CincoMasDescargados.Subido</code>.
	 */
	public void setSubido(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>agenda.CincoMasDescargados.Subido</code>.
	 */
	public java.lang.String getSubido() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>agenda.CincoMasDescargados.Descargas</code>.
	 */
	public void setDescargas(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>agenda.CincoMasDescargados.Descargas</code>.
	 */
	public java.lang.Integer getDescargas() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>agenda.CincoMasDescargados.Calificacion</code>.
	 */
	public void setCalificacion(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>agenda.CincoMasDescargados.Calificacion</code>.
	 */
	public java.lang.Double getCalificacion() {
		return (java.lang.Double) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Double> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Double> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.untref.agendauniversitaria.model.tables.Cincomasdescargados.CINCOMASDESCARGADOS.DOCUMENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.untref.agendauniversitaria.model.tables.Cincomasdescargados.CINCOMASDESCARGADOS.MATERIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.untref.agendauniversitaria.model.tables.Cincomasdescargados.CINCOMASDESCARGADOS.SUBIDO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return org.untref.agendauniversitaria.model.tables.Cincomasdescargados.CINCOMASDESCARGADOS.DESCARGAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field5() {
		return org.untref.agendauniversitaria.model.tables.Cincomasdescargados.CINCOMASDESCARGADOS.CALIFICACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getDocumento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getMateria();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSubido();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getDescargas();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value5() {
		return getCalificacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CincomasdescargadosRecord value1(java.lang.String value) {
		setDocumento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CincomasdescargadosRecord value2(java.lang.String value) {
		setMateria(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CincomasdescargadosRecord value3(java.lang.String value) {
		setSubido(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CincomasdescargadosRecord value4(java.lang.Integer value) {
		setDescargas(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CincomasdescargadosRecord value5(java.lang.Double value) {
		setCalificacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CincomasdescargadosRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.lang.Double value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CincomasdescargadosRecord
	 */
	public CincomasdescargadosRecord() {
		super(org.untref.agendauniversitaria.model.tables.Cincomasdescargados.CINCOMASDESCARGADOS);
	}

	/**
	 * Create a detached, initialised CincomasdescargadosRecord
	 */
	public CincomasdescargadosRecord(java.lang.String documento, java.lang.String materia, java.lang.String subido, java.lang.Integer descargas, java.lang.Double calificacion) {
		super(org.untref.agendauniversitaria.model.tables.Cincomasdescargados.CINCOMASDESCARGADOS);

		setValue(0, documento);
		setValue(1, materia);
		setValue(2, subido);
		setValue(3, descargas);
		setValue(4, calificacion);
	}
}
