/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MateriasRecord extends org.jooq.impl.TableRecordImpl<org.untref.agendauniversitaria.model.tables.records.MateriasRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1090502615;

	/**
	 * Setter for <code>agenda.Materias.IdMateria</code>.
	 */
	public void setIdmateria(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>agenda.Materias.IdMateria</code>.
	 */
	public java.lang.Integer getIdmateria() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>agenda.Materias.DescripMateria</code>.
	 */
	public void setDescripmateria(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>agenda.Materias.DescripMateria</code>.
	 */
	public java.lang.String getDescripmateria() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.untref.agendauniversitaria.model.tables.Materias.MATERIAS.IDMATERIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.untref.agendauniversitaria.model.tables.Materias.MATERIAS.DESCRIPMATERIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdmateria();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDescripmateria();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MateriasRecord value1(java.lang.Integer value) {
		setIdmateria(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MateriasRecord value2(java.lang.String value) {
		setDescripmateria(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MateriasRecord values(java.lang.Integer value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MateriasRecord
	 */
	public MateriasRecord() {
		super(org.untref.agendauniversitaria.model.tables.Materias.MATERIAS);
	}

	/**
	 * Create a detached, initialised MateriasRecord
	 */
	public MateriasRecord(java.lang.Integer idmateria, java.lang.String descripmateria) {
		super(org.untref.agendauniversitaria.model.tables.Materias.MATERIAS);

		setValue(0, idmateria);
		setValue(1, descripmateria);
	}
}
