/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alumnos implements java.io.Serializable {

	private static final long serialVersionUID = 395631720;

	private java.lang.Integer id;
	private java.lang.String  nombre;
	private java.lang.String  password;
	private java.lang.String  email;

	public Alumnos() {}

	public Alumnos(
		java.lang.Integer id,
		java.lang.String  nombre,
		java.lang.String  password,
		java.lang.String  email
	) {
		this.id = id;
		this.nombre = nombre;
		this.password = password;
		this.email = email;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getPassword() {
		return this.password;
	}

	public void setPassword(java.lang.String password) {
		this.password = password;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}
}
