/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Materias implements java.io.Serializable {

	private static final long serialVersionUID = -1650691153;

	private java.lang.Integer idmateria;
	private java.lang.String  descripmateria;

	public Materias() {}

	public Materias(
		java.lang.Integer idmateria,
		java.lang.String  descripmateria
	) {
		this.idmateria = idmateria;
		this.descripmateria = descripmateria;
	}

	public java.lang.Integer getIdmateria() {
		return this.idmateria;
	}

	public void setIdmateria(java.lang.Integer idmateria) {
		this.idmateria = idmateria;
	}

	public java.lang.String getDescripmateria() {
		return this.descripmateria;
	}

	public void setDescripmateria(java.lang.String descripmateria) {
		this.descripmateria = descripmateria;
	}
}
