/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlumnosRecord extends org.jooq.impl.TableRecordImpl<org.untref.agendauniversitaria.tables.records.AlumnosRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String[], java.lang.String[], java.lang.String[]> {

	private static final long serialVersionUID = 127870909;

	/**
	 * Setter for <code>agenda.alumnos.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>agenda.alumnos.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>agenda.alumnos.Nombre</code>.
	 */
	public void setNombre(java.lang.String[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>agenda.alumnos.Nombre</code>.
	 */
	public java.lang.String[] getNombre() {
		return (java.lang.String[]) getValue(1);
	}

	/**
	 * Setter for <code>agenda.alumnos.password</code>.
	 */
	public void setPassword(java.lang.String[] value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>agenda.alumnos.password</code>.
	 */
	public java.lang.String[] getPassword() {
		return (java.lang.String[]) getValue(2);
	}

	/**
	 * Setter for <code>agenda.alumnos.email</code>.
	 */
	public void setEmail(java.lang.String[] value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>agenda.alumnos.email</code>.
	 */
	public java.lang.String[] getEmail() {
		return (java.lang.String[]) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String[], java.lang.String[], java.lang.String[]> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String[], java.lang.String[], java.lang.String[]> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.untref.agendauniversitaria.tables.Alumnos.ALUMNOS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String[]> field2() {
		return org.untref.agendauniversitaria.tables.Alumnos.ALUMNOS.NOMBRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String[]> field3() {
		return org.untref.agendauniversitaria.tables.Alumnos.ALUMNOS.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String[]> field4() {
		return org.untref.agendauniversitaria.tables.Alumnos.ALUMNOS.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String[] value2() {
		return getNombre();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String[] value3() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String[] value4() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlumnosRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlumnosRecord value2(java.lang.String[] value) {
		setNombre(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlumnosRecord value3(java.lang.String[] value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlumnosRecord value4(java.lang.String[] value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlumnosRecord values(java.lang.Integer value1, java.lang.String[] value2, java.lang.String[] value3, java.lang.String[] value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AlumnosRecord
	 */
	public AlumnosRecord() {
		super(org.untref.agendauniversitaria.tables.Alumnos.ALUMNOS);
	}

	/**
	 * Create a detached, initialised AlumnosRecord
	 */
	public AlumnosRecord(java.lang.Integer id, java.lang.String[] nombre, java.lang.String[] password, java.lang.String[] email) {
		super(org.untref.agendauniversitaria.tables.Alumnos.ALUMNOS);

		setValue(0, id);
		setValue(1, nombre);
		setValue(2, password);
		setValue(3, email);
	}
}
