/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlumnomateriaRecord extends org.jooq.impl.TableRecordImpl<org.untref.agendauniversitaria.tables.records.AlumnomateriaRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 758691599;

	/**
	 * Setter for <code>agenda.AlumnoMateria.IdMateria</code>.
	 */
	public void setIdmateria(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>agenda.AlumnoMateria.IdMateria</code>.
	 */
	public java.lang.Integer getIdmateria() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>agenda.AlumnoMateria.IdUsuario</code>.
	 */
	public void setIdusuario(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>agenda.AlumnoMateria.IdUsuario</code>.
	 */
	public java.lang.Integer getIdusuario() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.untref.agendauniversitaria.tables.Alumnomateria.ALUMNOMATERIA.IDMATERIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.untref.agendauniversitaria.tables.Alumnomateria.ALUMNOMATERIA.IDUSUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdmateria();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIdusuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlumnomateriaRecord value1(java.lang.Integer value) {
		setIdmateria(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlumnomateriaRecord value2(java.lang.Integer value) {
		setIdusuario(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlumnomateriaRecord values(java.lang.Integer value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AlumnomateriaRecord
	 */
	public AlumnomateriaRecord() {
		super(org.untref.agendauniversitaria.tables.Alumnomateria.ALUMNOMATERIA);
	}

	/**
	 * Create a detached, initialised AlumnomateriaRecord
	 */
	public AlumnomateriaRecord(java.lang.Integer idmateria, java.lang.Integer idusuario) {
		super(org.untref.agendauniversitaria.tables.Alumnomateria.ALUMNOMATERIA);

		setValue(0, idmateria);
		setValue(1, idusuario);
	}
}
