/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventosRecord extends org.jooq.impl.TableRecordImpl<org.untref.agendauniversitaria.tables.records.EventosRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String[], java.sql.Timestamp, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 743982572;

	/**
	 * Setter for <code>agenda.Eventos.IdEvento</code>.
	 */
	public void setIdevento(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>agenda.Eventos.IdEvento</code>.
	 */
	public java.lang.Integer getIdevento() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>agenda.Eventos.DescripEvento</code>.
	 */
	public void setDescripevento(java.lang.String[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>agenda.Eventos.DescripEvento</code>.
	 */
	public java.lang.String[] getDescripevento() {
		return (java.lang.String[]) getValue(1);
	}

	/**
	 * Setter for <code>agenda.Eventos.FechaEvento</code>.
	 */
	public void setFechaevento(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>agenda.Eventos.FechaEvento</code>.
	 */
	public java.sql.Timestamp getFechaevento() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>agenda.Eventos.IdUsuario</code>.
	 */
	public void setIdusuario(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>agenda.Eventos.IdUsuario</code>.
	 */
	public java.lang.Integer getIdusuario() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>agenda.Eventos.IdMateria</code>.
	 */
	public void setIdmateria(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>agenda.Eventos.IdMateria</code>.
	 */
	public java.lang.Integer getIdmateria() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String[], java.sql.Timestamp, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String[], java.sql.Timestamp, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.untref.agendauniversitaria.tables.Eventos.EVENTOS.IDEVENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String[]> field2() {
		return org.untref.agendauniversitaria.tables.Eventos.EVENTOS.DESCRIPEVENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return org.untref.agendauniversitaria.tables.Eventos.EVENTOS.FECHAEVENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return org.untref.agendauniversitaria.tables.Eventos.EVENTOS.IDUSUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return org.untref.agendauniversitaria.tables.Eventos.EVENTOS.IDMATERIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdevento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String[] value2() {
		return getDescripevento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getFechaevento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getIdusuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getIdmateria();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventosRecord value1(java.lang.Integer value) {
		setIdevento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventosRecord value2(java.lang.String[] value) {
		setDescripevento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventosRecord value3(java.sql.Timestamp value) {
		setFechaevento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventosRecord value4(java.lang.Integer value) {
		setIdusuario(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventosRecord value5(java.lang.Integer value) {
		setIdmateria(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventosRecord values(java.lang.Integer value1, java.lang.String[] value2, java.sql.Timestamp value3, java.lang.Integer value4, java.lang.Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventosRecord
	 */
	public EventosRecord() {
		super(org.untref.agendauniversitaria.tables.Eventos.EVENTOS);
	}

	/**
	 * Create a detached, initialised EventosRecord
	 */
	public EventosRecord(java.lang.Integer idevento, java.lang.String[] descripevento, java.sql.Timestamp fechaevento, java.lang.Integer idusuario, java.lang.Integer idmateria) {
		super(org.untref.agendauniversitaria.tables.Eventos.EVENTOS);

		setValue(0, idevento);
		setValue(1, descripevento);
		setValue(2, fechaevento);
		setValue(3, idusuario);
		setValue(4, idmateria);
	}
}
