/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alumnomateria extends org.jooq.impl.TableImpl<org.untref.agendauniversitaria.model.tables.records.AlumnomateriaRecord> {

	private static final long serialVersionUID = 374679567;

	/**
	 * The singleton instance of <code>agenda.AlumnoMateria</code>
	 */
	public static final org.untref.agendauniversitaria.model.tables.Alumnomateria ALUMNOMATERIA = new org.untref.agendauniversitaria.model.tables.Alumnomateria();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.untref.agendauniversitaria.model.tables.records.AlumnomateriaRecord> getRecordType() {
		return org.untref.agendauniversitaria.model.tables.records.AlumnomateriaRecord.class;
	}

	/**
	 * The column <code>agenda.AlumnoMateria.IdMateria</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.model.tables.records.AlumnomateriaRecord, java.lang.Integer> IDMATERIA = createField("IdMateria", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>agenda.AlumnoMateria.IdUsuario</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.model.tables.records.AlumnomateriaRecord, java.lang.Integer> IDUSUARIO = createField("IdUsuario", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>agenda.AlumnoMateria</code> table reference
	 */
	public Alumnomateria() {
		this("AlumnoMateria", null);
	}

	/**
	 * Create an aliased <code>agenda.AlumnoMateria</code> table reference
	 */
	public Alumnomateria(java.lang.String alias) {
		this(alias, org.untref.agendauniversitaria.model.tables.Alumnomateria.ALUMNOMATERIA);
	}

	private Alumnomateria(java.lang.String alias, org.jooq.Table<org.untref.agendauniversitaria.model.tables.records.AlumnomateriaRecord> aliased) {
		this(alias, aliased, null);
	}

	private Alumnomateria(java.lang.String alias, org.jooq.Table<org.untref.agendauniversitaria.model.tables.records.AlumnomateriaRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.untref.agendauniversitaria.model.Agenda.AGENDA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.untref.agendauniversitaria.model.tables.Alumnomateria as(java.lang.String alias) {
		return new org.untref.agendauniversitaria.model.tables.Alumnomateria(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.untref.agendauniversitaria.model.tables.Alumnomateria rename(java.lang.String name) {
		return new org.untref.agendauniversitaria.model.tables.Alumnomateria(name, null);
	}
}
