/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alumnos extends org.jooq.impl.TableImpl<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord> {

	private static final long serialVersionUID = -1172029907;

	/**
	 * The singleton instance of <code>agenda.alumnos</code>
	 */
	public static final org.untref.agendauniversitaria.model.tables.Alumnos ALUMNOS = new org.untref.agendauniversitaria.model.tables.Alumnos();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord> getRecordType() {
		return org.untref.agendauniversitaria.model.tables.records.AlumnosRecord.class;
	}

	/**
	 * The column <code>agenda.alumnos.ID</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>agenda.alumnos.Nombre</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord, java.lang.String> NOMBRE = createField("Nombre", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>agenda.alumnos.password</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>agenda.alumnos.email</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>agenda.alumnos</code> table reference
	 */
	public Alumnos() {
		this("alumnos", null);
	}

	/**
	 * Create an aliased <code>agenda.alumnos</code> table reference
	 */
	public Alumnos(java.lang.String alias) {
		this(alias, org.untref.agendauniversitaria.model.tables.Alumnos.ALUMNOS);
	}

	private Alumnos(java.lang.String alias, org.jooq.Table<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord> aliased) {
		this(alias, aliased, null);
	}

	private Alumnos(java.lang.String alias, org.jooq.Table<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.untref.agendauniversitaria.model.Agenda.AGENDA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord> getPrimaryKey() {
		return org.untref.agendauniversitaria.model.Keys.KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord>>asList(org.untref.agendauniversitaria.model.Keys.KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.untref.agendauniversitaria.model.tables.Alumnos as(java.lang.String alias) {
		return new org.untref.agendauniversitaria.model.tables.Alumnos(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.untref.agendauniversitaria.model.tables.Alumnos rename(java.lang.String name) {
		return new org.untref.agendauniversitaria.model.tables.Alumnos(name, null);
	}
}
