/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Eventos extends org.jooq.impl.TableImpl<org.untref.agendauniversitaria.model.tables.records.EventosRecord> {

	private static final long serialVersionUID = -129087772;

	/**
	 * The singleton instance of <code>agenda.Eventos</code>
	 */
	public static final org.untref.agendauniversitaria.model.tables.Eventos EVENTOS = new org.untref.agendauniversitaria.model.tables.Eventos();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.untref.agendauniversitaria.model.tables.records.EventosRecord> getRecordType() {
		return org.untref.agendauniversitaria.model.tables.records.EventosRecord.class;
	}

	/**
	 * The column <code>agenda.Eventos.IdEvento</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.model.tables.records.EventosRecord, java.lang.Integer> IDEVENTO = createField("IdEvento", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>agenda.Eventos.DescripEvento</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.model.tables.records.EventosRecord, java.lang.String> DESCRIPEVENTO = createField("DescripEvento", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>agenda.Eventos.FechaEvento</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.model.tables.records.EventosRecord, java.sql.Timestamp> FECHAEVENTO = createField("FechaEvento", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>agenda.Eventos.IdUsuario</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.model.tables.records.EventosRecord, java.lang.Integer> IDUSUARIO = createField("IdUsuario", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>agenda.Eventos.IdMateria</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.model.tables.records.EventosRecord, java.lang.Integer> IDMATERIA = createField("IdMateria", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>agenda.Eventos</code> table reference
	 */
	public Eventos() {
		this("Eventos", null);
	}

	/**
	 * Create an aliased <code>agenda.Eventos</code> table reference
	 */
	public Eventos(java.lang.String alias) {
		this(alias, org.untref.agendauniversitaria.model.tables.Eventos.EVENTOS);
	}

	private Eventos(java.lang.String alias, org.jooq.Table<org.untref.agendauniversitaria.model.tables.records.EventosRecord> aliased) {
		this(alias, aliased, null);
	}

	private Eventos(java.lang.String alias, org.jooq.Table<org.untref.agendauniversitaria.model.tables.records.EventosRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.untref.agendauniversitaria.model.Agenda.AGENDA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.untref.agendauniversitaria.model.tables.records.EventosRecord> getPrimaryKey() {
		return org.untref.agendauniversitaria.model.Keys.EVENTOS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.untref.agendauniversitaria.model.tables.records.EventosRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.untref.agendauniversitaria.model.tables.records.EventosRecord>>asList(org.untref.agendauniversitaria.model.Keys.EVENTOS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.untref.agendauniversitaria.model.tables.Eventos as(java.lang.String alias) {
		return new org.untref.agendauniversitaria.model.tables.Eventos(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.untref.agendauniversitaria.model.tables.Eventos rename(java.lang.String name) {
		return new org.untref.agendauniversitaria.model.tables.Eventos(name, null);
	}
}
