/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cincomasdescargados extends org.jooq.impl.TableImpl<org.untref.agendauniversitaria.tables.records.CincomasdescargadosRecord> {

	private static final long serialVersionUID = -647401102;

	/**
	 * The singleton instance of <code>agenda.CincoMasDescargados</code>
	 */
	public static final org.untref.agendauniversitaria.tables.Cincomasdescargados CINCOMASDESCARGADOS = new org.untref.agendauniversitaria.tables.Cincomasdescargados();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.untref.agendauniversitaria.tables.records.CincomasdescargadosRecord> getRecordType() {
		return org.untref.agendauniversitaria.tables.records.CincomasdescargadosRecord.class;
	}

	/**
	 * The column <code>agenda.CincoMasDescargados.Documento</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.tables.records.CincomasdescargadosRecord, java.lang.String[]> DOCUMENTO = createField("Documento", org.jooq.impl.SQLDataType.CHAR.getArrayDataType(), this, "");

	/**
	 * The column <code>agenda.CincoMasDescargados.Materia</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.tables.records.CincomasdescargadosRecord, java.lang.String[]> MATERIA = createField("Materia", org.jooq.impl.SQLDataType.CHAR.getArrayDataType(), this, "");

	/**
	 * The column <code>agenda.CincoMasDescargados.Subido</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.tables.records.CincomasdescargadosRecord, java.lang.String[]> SUBIDO = createField("Subido", org.jooq.impl.SQLDataType.CHAR.getArrayDataType(), this, "");

	/**
	 * The column <code>agenda.CincoMasDescargados.Descargas</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.tables.records.CincomasdescargadosRecord, java.lang.Integer> DESCARGAS = createField("Descargas", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>agenda.CincoMasDescargados.Calificacion</code>.
	 */
	public final org.jooq.TableField<org.untref.agendauniversitaria.tables.records.CincomasdescargadosRecord, java.lang.Double> CALIFICACION = createField("Calificacion", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * Create a <code>agenda.CincoMasDescargados</code> table reference
	 */
	public Cincomasdescargados() {
		this("CincoMasDescargados", null);
	}

	/**
	 * Create an aliased <code>agenda.CincoMasDescargados</code> table reference
	 */
	public Cincomasdescargados(java.lang.String alias) {
		this(alias, org.untref.agendauniversitaria.tables.Cincomasdescargados.CINCOMASDESCARGADOS);
	}

	private Cincomasdescargados(java.lang.String alias, org.jooq.Table<org.untref.agendauniversitaria.tables.records.CincomasdescargadosRecord> aliased) {
		this(alias, aliased, null);
	}

	private Cincomasdescargados(java.lang.String alias, org.jooq.Table<org.untref.agendauniversitaria.tables.records.CincomasdescargadosRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.untref.agendauniversitaria.Agenda.AGENDA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.untref.agendauniversitaria.tables.Cincomasdescargados as(java.lang.String alias) {
		return new org.untref.agendauniversitaria.tables.Cincomasdescargados(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.untref.agendauniversitaria.tables.Cincomasdescargados rename(java.lang.String name) {
		return new org.untref.agendauniversitaria.tables.Cincomasdescargados(name, null);
	}
}
