/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alumnomateria implements java.io.Serializable {

	private static final long serialVersionUID = 796135029;

	private java.lang.Integer idmateria;
	private java.lang.Integer idusuario;

	public Alumnomateria() {}

	public Alumnomateria(
		java.lang.Integer idmateria,
		java.lang.Integer idusuario
	) {
		this.idmateria = idmateria;
		this.idusuario = idusuario;
	}

	public java.lang.Integer getIdmateria() {
		return this.idmateria;
	}

	public void setIdmateria(java.lang.Integer idmateria) {
		this.idmateria = idmateria;
	}

	public java.lang.Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(java.lang.Integer idusuario) {
		this.idusuario = idusuario;
	}
}
