/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Documentos implements java.io.Serializable {

	private static final long serialVersionUID = 710528469;

	private java.lang.Integer  id;
	private java.lang.String[] descripcion;
	private java.lang.String[] url;
	private java.lang.Integer  cantdescargas;
	private java.lang.Integer  iduploader;
	private java.lang.Integer  idmateria;
	private java.lang.Double   calificacionpromedio;

	public Documentos() {}

	public Documentos(
		java.lang.Integer  id,
		java.lang.String[] descripcion,
		java.lang.String[] url,
		java.lang.Integer  cantdescargas,
		java.lang.Integer  iduploader,
		java.lang.Integer  idmateria,
		java.lang.Double   calificacionpromedio
	) {
		this.id = id;
		this.descripcion = descripcion;
		this.url = url;
		this.cantdescargas = cantdescargas;
		this.iduploader = iduploader;
		this.idmateria = idmateria;
		this.calificacionpromedio = calificacionpromedio;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String[] getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(java.lang.String[] descripcion) {
		this.descripcion = descripcion;
	}

	public java.lang.String[] getUrl() {
		return this.url;
	}

	public void setUrl(java.lang.String[] url) {
		this.url = url;
	}

	public java.lang.Integer getCantdescargas() {
		return this.cantdescargas;
	}

	public void setCantdescargas(java.lang.Integer cantdescargas) {
		this.cantdescargas = cantdescargas;
	}

	public java.lang.Integer getIduploader() {
		return this.iduploader;
	}

	public void setIduploader(java.lang.Integer iduploader) {
		this.iduploader = iduploader;
	}

	public java.lang.Integer getIdmateria() {
		return this.idmateria;
	}

	public void setIdmateria(java.lang.Integer idmateria) {
		this.idmateria = idmateria;
	}

	public java.lang.Double getCalificacionpromedio() {
		return this.calificacionpromedio;
	}

	public void setCalificacionpromedio(java.lang.Double calificacionpromedio) {
		this.calificacionpromedio = calificacionpromedio;
	}
}
