/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Eventos implements java.io.Serializable {

	private static final long serialVersionUID = -136234186;

	private java.lang.Integer  idevento;
	private java.lang.String[] descripevento;
	private java.sql.Timestamp fechaevento;
	private java.lang.Integer  idusuario;
	private java.lang.Integer  idmateria;

	public Eventos() {}

	public Eventos(
		java.lang.Integer  idevento,
		java.lang.String[] descripevento,
		java.sql.Timestamp fechaevento,
		java.lang.Integer  idusuario,
		java.lang.Integer  idmateria
	) {
		this.idevento = idevento;
		this.descripevento = descripevento;
		this.fechaevento = fechaevento;
		this.idusuario = idusuario;
		this.idmateria = idmateria;
	}

	public java.lang.Integer getIdevento() {
		return this.idevento;
	}

	public void setIdevento(java.lang.Integer idevento) {
		this.idevento = idevento;
	}

	public java.lang.String[] getDescripevento() {
		return this.descripevento;
	}

	public void setDescripevento(java.lang.String[] descripevento) {
		this.descripevento = descripevento;
	}

	public java.sql.Timestamp getFechaevento() {
		return this.fechaevento;
	}

	public void setFechaevento(java.sql.Timestamp fechaevento) {
		this.fechaevento = fechaevento;
	}

	public java.lang.Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(java.lang.Integer idusuario) {
		this.idusuario = idusuario;
	}

	public java.lang.Integer getIdmateria() {
		return this.idmateria;
	}

	public void setIdmateria(java.lang.Integer idmateria) {
		this.idmateria = idmateria;
	}
}
