/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.model;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>agenda</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord> KEY = UniqueKeys0.KEY;
	public static final org.jooq.UniqueKey<org.untref.agendauniversitaria.model.tables.records.EventosRecord> EVENTOS_PKEY = UniqueKeys0.EVENTOS_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<org.untref.agendauniversitaria.model.tables.records.AlumnosRecord> KEY = createUniqueKey(org.untref.agendauniversitaria.model.tables.Alumnos.ALUMNOS, org.untref.agendauniversitaria.model.tables.Alumnos.ALUMNOS.ID);
		public static final org.jooq.UniqueKey<org.untref.agendauniversitaria.model.tables.records.EventosRecord> EVENTOS_PKEY = createUniqueKey(org.untref.agendauniversitaria.model.tables.Eventos.EVENTOS, org.untref.agendauniversitaria.model.tables.Eventos.EVENTOS.IDEVENTO);
	}
}
