/**
 * This class is generated by jOOQ
 */
package org.untref.agendauniversitaria.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in agenda
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table agenda.AlumnoMateria
	 */
	public static final org.untref.agendauniversitaria.model.tables.Alumnomateria ALUMNOMATERIA = org.untref.agendauniversitaria.model.tables.Alumnomateria.ALUMNOMATERIA;

	/**
	 * The table agenda.alumnos
	 */
	public static final org.untref.agendauniversitaria.model.tables.Alumnos ALUMNOS = org.untref.agendauniversitaria.model.tables.Alumnos.ALUMNOS;

	/**
	 * The table agenda.CincoMasDescargados
	 */
	public static final org.untref.agendauniversitaria.model.tables.Cincomasdescargados CINCOMASDESCARGADOS = org.untref.agendauniversitaria.model.tables.Cincomasdescargados.CINCOMASDESCARGADOS;

	/**
	 * The table agenda.documentos
	 */
	public static final org.untref.agendauniversitaria.model.tables.Documentos DOCUMENTOS = org.untref.agendauniversitaria.model.tables.Documentos.DOCUMENTOS;

	/**
	 * The table agenda.Eventos
	 */
	public static final org.untref.agendauniversitaria.model.tables.Eventos EVENTOS = org.untref.agendauniversitaria.model.tables.Eventos.EVENTOS;

	/**
	 * The table agenda.Materias
	 */
	public static final org.untref.agendauniversitaria.model.tables.Materias MATERIAS = org.untref.agendauniversitaria.model.tables.Materias.MATERIAS;
}
